name: CI

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  # Job 1: Build and Push to Docker Hub
  build:
    runs-on: ubuntu-latest
    
    # Step 1: Check out the code from the repository
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    # Step 2: Set up .NET
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
    
    # Step 3: Build the .NET projects
    - name: Build ShoppingCartApi Project
      run: dotnet build ShoppingCartApi/ShoppingCartApi.csproj --configuration Release

    - name: Build ShoppingCartWeb Project
      run: dotnet build ShoppingCartWeb/ShoppingCartWeb.csproj --configuration Release

    - name: Build ProductApi Project
      run: dotnet build ProductApi/ProductApi.csproj --configuration Release

    # Step 4: Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Step 5: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 6: Build and push the ShoppingCartApi Docker image
    - name: Build and push ShoppingCartApi Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/shoppingcartapi:latest -f ShoppingCartApi/Dockerfile .
        docker push ${{ secrets.DOCKER_USERNAME }}/shoppingcartapi:latest

    # Step 7: Build and push the ShoppingCartWeb Docker image
    - name: Build and push ShoppingCartWeb Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/shoppingcartweb:latest -f ShoppingCartWeb/Dockerfile .
        docker push ${{ secrets.DOCKER_USERNAME }}/shoppingcartweb:latest

    # Step 8: Build and push the ProductApi Docker image
    - name: Build and push ProductApi Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/productapi:latest -f ProductApi/Dockerfile .
        docker push ${{ secrets.DOCKER_USERNAME }}/productapi:latest

  snyk:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Snyk CLI
        uses: snyk/actions/setup@v2
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Snyk Code Test
        run: snyk code test --sarif-file-output=snyk-code.sarif

      - name: Upload Snyk Code results to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-code.sarif

      - name: Snyk Open Source Test
        run: snyk test --all-projects --sarif-file-output=snyk-open-source.sarif

      - name: Upload Snyk Open Source results to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-open-source.sarif

      - name: Snyk Container Test
        run: snyk container test ${{ secrets.DOCKER_USERNAME }}/shoppingcartapi:latest --file=ShoppingCartApi/Dockerfile --sarif-file-output=snyk-container.sarif

      - name: Upload Snyk Container results to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-container.sarif